### ISSUE TITLE
Latest kernel 4.5.1 won't boot to graphical desktop in VirtualBox VM

### ISSUE THREAD

**Issue by gajama** [Antergos/lightdm-webkit2-greeter#35] opened 2016-04-15 09:53 UTC
I run Antergos within a VirtualBox VM on a PC running Windows.

After the latest updates the system hangs at trying to launch lightdm - systemctl fails to start the lightdm service. I also tried gdm instead and this also failed.

After a bit of investigation this appears to be a VirtualBox issue - [https://forums.virtualbox.org/viewtopic.php?f=3&t=76908&sid=9f746447b9ba367449ce5a33cfdce946&start=15#p358435] - that can be worked around by adding the kernel parameter `iomem=relaxed` until VirtualBox is updated.

**Comment by odious** [comment] 2016-04-18 09:22
Can confirm. Antergos in a Virtualbox VM won't start LightDM. The kernel parameter suggested by OP "solved" the issue.

**Comment by lots0logs** [comment] 2016-04-18 11:15
The issue is a virtualbox bug. Closing...

**Closed by lots0logs** 2016-04-18 11:15 UTC
Labels: invalid

**Comment by OEvgeny** [comment] 2016-04-25 05:25
Seems to be fixed in 5.0.18. But Ategros is not working for me.
